export enum ActionType {
  NEW_GAME = "NEW_GAME",
  RESET_GAME = "RESET_GAME",
  SOLVE_GAME = "SOLVE_GAME",
  PLACE_INPUT = "PLACE_INPUT",
  CLEAR_INPUT = "CLEAR_INPUT",
  SELECT_SQUARE = "SELECT_SQUARE",
  CHANGE_DIFFICULTY = "CHANGE_DIFFUCLTY",
  UNDO_INPUT = "UNDO_INPUT",
  REDO_INPUT = "REDO_INPUT",
  PAUSE_GAME = "PAUSE_GAME",
  RESUME_GAME = "RESUME_GAME",
}
